vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /photos
            upload_destination: '%kernel.project_dir%/public/pictures/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer